"""Initial Migration

Revision ID: 360cf6e84f24
Revises: cd77dbe3c5e4
Create Date: 2021-02-24 11:16:22.569291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360cf6e84f24'
down_revision = 'cd77dbe3c5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
